/**
 * Hardware identifier values that are known placeholders, OEM defaults, or
 * are shared across thousands of devices. Banning any of these would result
 * in mass false-positive bans.
 *
 * Comparison is always case-insensitive (values stored lowercase here).
 */
const UNSAFE_HWID_LIST = [
  "Default string",
  "System Serial Number",
  "To Be Filled By O.E.M.",
  "To be filled by O.E.M.",
  "To Be Filled By OEM",
  "To be filled by OEM",
  "OEM",
  "OEM String",
  "None",
  "Unknown",
  "Unknown Serial",
  "Not Specified",
  "Not Applicable",
  "N/A",
  "NA",
  "Invalid",
  "Undefined",
  "Empty",
  "Null",
  "123456789",
  "0123456789",
  "1234567890",
  "0000000000",
  "00000000",
  "FFFFFFFF",
  "FFFFFFFFFFFF",
  "Default",
  "Base Board Serial",
  "System Product Name",
  "System Version",
  "SerialNumber",
  "Serial Number",
  "No Asset Tag",
  "Asset Tag",
  "SKU",
  "Type1ProductConfigId",
  "Chassis Serial Number",
  "Board Serial Number",
  "1234567",
  "12345678",
  "123456789ABCDEF",
  "ABCDEFG",
  "ABCDEF123456",
  "Filled By O.E.M.",
  "Reserved",
  "Unavailable",
  "Not Available",
  "NO SERIAL",
  "NO_SERIAL",
  "NO-SERIAL",
  "NONE",
  "NULL",
  "0",
  "1",
  "A",
  "AA",
  "AAA",
  "EMPTY",
  "INVALID",
  "DEFAULT",
  "STRING",
  "SERIAL",
  "SERIALNUMBER",
  "123123123",
  "111111111",
  "222222222",
  "999999999",
  "FFFFFFFFFFFFFFFF",
  "FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF",
  "00000000-0000-0000-0000-000000000000",
  "VMware",
  "Virtual Machine",
  "VirtualBox",
  "QEMU",
  "KVM",
  "BOCHS",
  "Xen",
  "Parallels",
  "innotek GmbH",
  "Microsoft Corporation",
  "Standard PC",
  "Default System BIOS",
  "American Megatrends Inc.",
  "Phoenix Technologies",
  "SeaBIOS",
];

export const UNSAFE_HWID_HASHES = new Set(
  UNSAFE_HWID_LIST.map((s) => s.toLowerCase()),
);

/** Returns true if the hash is a known placeholder / OEM default value. */
export function isUnsafeHwid(hash: string): boolean {
  return UNSAFE_HWID_HASHES.has(hash.trim().toLowerCase());
}
